version: '3'
services:
  browserless:
    image: browserless/chrome:latest
    ports:
      - "9222:3000"
    environment:
      - MAX_CONCURRENT_SESSIONS=10
      - MAX_QUEUE_COUNT=5
      - PREBOOT_CHROME=true
      - KEEP_ALIVE=true
      - CHROME_REFRESH_SECONDS=3600
    restart: always
